[package]
name = "aeb_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
micromath = "2.0.0"
heapless = "0.7.16"
line_drawing = "1.0.0"

[dev-dependencies]
ld06-embed = { git = "https://github.com/andyblarblar/LD06-embed" }
linux-embedded-hal = "0.3.2"
nalgebra = "0.31.2"